name: accenture_photobooth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  provider: ^6.1.2
  supabase_flutter: ^2.3.0
  google_generative_ai: ^0.4.7
  http: ^1.1.0
  uuid: ^4.3.3
  image: ^4.2.0
  flutter_dotenv: ^5.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: GraphikTrial
      fonts:
        - asset: assets/fonts/Graphik-Black-Trial.otf
        - asset: assets/fonts/Graphik-Bold-Trial.otf
        - asset: assets/fonts/Graphik-Light-Trial.otf
        - asset: assets/fonts/Graphik-Medium-Trial.otf
        - asset: assets/fonts/Graphik-Regular-Trial.otf
        - asset: assets/fonts/Graphik-Semibold-Trial.otf